# Generated by Django 4.2 on 2023-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.TextField()),
                ('company', models.CharField(max_length=120, verbose_name='Company Name')),
                ('link', models.CharField(max_length=400)),
                ('post', models.CharField(default='2023-04-22', max_length=400)),
                ('description', models.TextField()),
                ('agency', models.BooleanField(default=False)),
            ],
        ),
    ]
